"use client";

import { persistor, store } from "@/features/store";
import { Inter } from "next/font/google";
import { usePathname, useRouter } from "next/navigation";
import { Toaster } from "react-hot-toast";
import { Provider } from "react-redux";
import { PersistGate } from "redux-persist/integration/react";
import Footer from "./_components/(footer)/footer";
import Navbar from "./_components/(navigation)/navbar";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const router = useRouter();
  // console user

  const pathname = usePathname();
  const isDashboardRoute = pathname.startsWith("/dashboard");
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider store={store}>
          <PersistGate loading={null} persistor={persistor}>
            <Toaster />
            {!isDashboardRoute && <Navbar />}
            <div>{children}</div>
            {!isDashboardRoute && <Footer />}
          </PersistGate>
        </Provider>
      </body>
    </html>
  );
}
