"use client";

import { Inter } from "next/font/google";
import { usePathname, useRouter } from "next/navigation";
import { Toaster } from "react-hot-toast";
import Navbar from "./_components/(navigation)/navbar";
import Providers from "./_components/Providers/providers";
import Footer from "./_components/footer";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const router = useRouter();
  const pathname = usePathname();
  const isDashboardRoute = pathname.startsWith("/dashboard");
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <Toaster />
          <Navbar />
          {/* {!isDashboardRoute && <Navbar />} */}
          {children}
          <Footer />
          {/* {!isDashboardRoute && <Footer />} */}
        </Providers>
      </body>
    </html>
  );
}
